apiVersion: v1
kind: Service
metadata:
  name: e2e-fastapi-react-booknook-staging
  namespace: colossus-e2e-fastapi-react-booknook-staging
  labels:
    app: e2e-fastapi-react-booknook-staging
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: e2e-fastapi-react-booknook-staging
  ports:
    - port: 80
      targetPort: 80
